on: [push, pull_request]

name: benches

jobs:
  test:
    name: benches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --all-features